#############################################################################
# Makefile for building: libfiletype.a
# Generated by qmake (3.1) (Qt 5.15.17)
# Project:  ../filetype/libfiletype.pro
# Template: lib
# Command: /usr/bin/qmake -o Makefile ../filetype/libfiletype.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DHAVE_CONFIG_H=1 -D_SSIZE_T_DEFINED=1 -DPCRE2_CODE_UNIT_WIDTH=8 -DHAVE_MKSTEMP=1
CFLAGS        = -pipe -O2 -fPIC -flto -fno-fat-lto-objects -Wall -Wextra $(DEFINES)
CXXFLAGS      = -pipe -O2 -fPIC -std=gnu++11 -flto -fno-fat-lto-objects -Wall -Wextra $(DEFINES)
INCPATH       = -I../filetype -I. -I../filetype/misc -I../filetype/file/src -I../filetype/pcre2/src -I/usr/lib/qt/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = filetype1.0.0
DISTDIR = /home/soramimi/develop/Guitar/.tmp/filetype1.0.0
AR            = gcc-ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../filetype/file/src/apprentice.c \
		../filetype/file/src/apptype.c \
		../filetype/file/src/ascmagic.c \
		../filetype/file/src/asctime_r.c \
		../filetype/file/src/asprintf.c \
		../filetype/file/src/buffer.c \
		../filetype/file/src/cdf.c \
		../filetype/file/src/cdf_time.c \
		../filetype/file/src/compress.c \
		../filetype/file/src/ctime_r.c \
		../filetype/file/src/der.c \
		../filetype/file/src/dprintf.c \
		../filetype/file/src/encoding.c \
		../filetype/file/src/fmtcheck.c \
		../filetype/file/src/fsmagic.c \
		../filetype/file/src/funcs.c \
		../filetype/file/src/getline.c \
		../filetype/file/src/gmtime_r.c \
		../filetype/file/src/is_csv.c \
		../filetype/file/src/is_json.c \
		../filetype/file/src/is_simh.c \
		../filetype/file/src/is_tar.c \
		../filetype/file/src/localtime_r.c \
		../filetype/file/src/magic.c \
		../filetype/file/src/pread.c \
		../filetype/file/src/print.c \
		../filetype/file/src/readcdf.c \
		../filetype/file/src/readelf.c \
		../filetype/file/src/seccomp.c \
		../filetype/file/src/softmagic.c \
		../filetype/file/src/strcasestr.c \
		../filetype/file/src/strlcat.c \
		../filetype/file/src/strlcpy.c \
		../filetype/file/src/vasprintf.c \
		../filetype/pcre2/src/pcre2_auto_possess.c \
		../filetype/pcre2/src/pcre2_compile.c \
		../filetype/pcre2/src/pcre2_config.c \
		../filetype/pcre2/src/pcre2_context.c \
		../filetype/pcre2/src/pcre2_convert.c \
		../filetype/pcre2/src/pcre2_dfa_match.c \
		../filetype/pcre2/src/pcre2_error.c \
		../filetype/pcre2/src/pcre2_find_bracket.c \
		../filetype/pcre2/src/pcre2_fuzzsupport.c \
		../filetype/pcre2/src/pcre2_jit_compile.c \
		../filetype/pcre2/src/pcre2_maketables.c \
		../filetype/pcre2/src/pcre2_match.c \
		../filetype/pcre2/src/pcre2_match_data.c \
		../filetype/pcre2/src/pcre2_newline.c \
		../filetype/pcre2/src/pcre2_ord2utf.c \
		../filetype/pcre2/src/pcre2_pattern_info.c \
		../filetype/pcre2/src/pcre2_serialize.c \
		../filetype/pcre2/src/pcre2_string_utils.c \
		../filetype/pcre2/src/pcre2_study.c \
		../filetype/pcre2/src/pcre2_substitute.c \
		../filetype/pcre2/src/pcre2_substring.c \
		../filetype/pcre2/src/pcre2_tables.c \
		../filetype/pcre2/src/pcre2_ucd.c \
		../filetype/pcre2/src/pcre2_valid_utf.c \
		../filetype/pcre2/src/pcre2_xclass.c \
		../filetype/pcre2/src/pcre2posix.c 
OBJECTS       = apprentice.o \
		apptype.o \
		ascmagic.o \
		asctime_r.o \
		asprintf.o \
		buffer.o \
		cdf.o \
		cdf_time.o \
		compress.o \
		ctime_r.o \
		der.o \
		dprintf.o \
		encoding.o \
		fmtcheck.o \
		fsmagic.o \
		funcs.o \
		getline.o \
		gmtime_r.o \
		is_csv.o \
		is_json.o \
		is_simh.o \
		is_tar.o \
		localtime_r.o \
		magic.o \
		pread.o \
		print.o \
		readcdf.o \
		readelf.o \
		seccomp.o \
		softmagic.o \
		strcasestr.o \
		strlcat.o \
		strlcpy.o \
		vasprintf.o \
		pcre2_auto_possess.o \
		pcre2_compile.o \
		pcre2_config.o \
		pcre2_context.o \
		pcre2_convert.o \
		pcre2_dfa_match.o \
		pcre2_error.o \
		pcre2_find_bracket.o \
		pcre2_fuzzsupport.o \
		pcre2_jit_compile.o \
		pcre2_maketables.o \
		pcre2_match.o \
		pcre2_match_data.o \
		pcre2_newline.o \
		pcre2_ord2utf.o \
		pcre2_pattern_info.o \
		pcre2_serialize.o \
		pcre2_string_utils.o \
		pcre2_study.o \
		pcre2_substitute.o \
		pcre2_substring.o \
		pcre2_tables.o \
		pcre2_ucd.o \
		pcre2_valid_utf.o \
		pcre2_xclass.o \
		pcre2posix.o
DIST          = /usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/sanitize.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_Attica.pri \
		/usr/lib/qt/mkspecs/modules/qt_BluezQt.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivities.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivitiesStats.pri \
		/usr/lib/qt/mkspecs/modules/qt_KArchive.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuth.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuthCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCMUtils.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCrash.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDeclarative.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDESu.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDNSSD.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDSoapClient.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDSoapServer.pri \
		/usr/lib/qt/mkspecs/modules/qt_KEmoticons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KFileMetaData.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KHolidays.pri \
		/usr/lib/qt/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIdleTime.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_Kirigami2.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemModels.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuff.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuffCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifyConfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib/qt/mkspecs/modules/qt_KParts.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPeople.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPeopleWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPty.pri \
		/usr/lib/qt/mkspecs/modules/qt_KRunner.pri \
		/usr/lib/qt/mkspecs/modules/qt_KService.pri \
		/usr/lib/qt/mkspecs/modules/qt_KSyntaxHighlighting.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextEditor.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KUnitConversion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWallet.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandClient.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandServer.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdf.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdf_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_phonon4qt5.pri \
		/usr/lib/qt/mkspecs/modules/qt_Prison.pri \
		/usr/lib/qt/mkspecs/modules/qt_QuickAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_Solid.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri \
		/usr/lib/qt/mkspecs/modules/qt_Syndication.pri \
		/usr/lib/qt/mkspecs/modules/qt_ThreadWeaver.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/toolchain.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/link_ltcg.prf \
		/usr/lib/qt/mkspecs/features/ltcg.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qmake_use.prf \
		/usr/lib/qt/mkspecs/features/file_copies.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		../filetype/libfiletype.pro file/src/cdf.h \
		file/src/der.h \
		file/src/elfclass.h \
		file/src/file.h \
		file/src/file_opts.h \
		file/src/patchlevel.h \
		file/src/readelf.h \
		file/src/tar.h \
		misc/config.h \
		misc/file_config.h \
		misc/pcre2.h \
		misc/pcre2_config.h \
		pcre2/src/pcre2_internal.h \
		pcre2/src/pcre2_intmodedep.h \
		pcre2/src/pcre2_ucp.h \
		pcre2/src/pcre2posix.h \
		pcre2/src/regex.h ../filetype/file/src/apprentice.c \
		../filetype/file/src/apptype.c \
		../filetype/file/src/ascmagic.c \
		../filetype/file/src/asctime_r.c \
		../filetype/file/src/asprintf.c \
		../filetype/file/src/buffer.c \
		../filetype/file/src/cdf.c \
		../filetype/file/src/cdf_time.c \
		../filetype/file/src/compress.c \
		../filetype/file/src/ctime_r.c \
		../filetype/file/src/der.c \
		../filetype/file/src/dprintf.c \
		../filetype/file/src/encoding.c \
		../filetype/file/src/fmtcheck.c \
		../filetype/file/src/fsmagic.c \
		../filetype/file/src/funcs.c \
		../filetype/file/src/getline.c \
		../filetype/file/src/gmtime_r.c \
		../filetype/file/src/is_csv.c \
		../filetype/file/src/is_json.c \
		../filetype/file/src/is_simh.c \
		../filetype/file/src/is_tar.c \
		../filetype/file/src/localtime_r.c \
		../filetype/file/src/magic.c \
		../filetype/file/src/pread.c \
		../filetype/file/src/print.c \
		../filetype/file/src/readcdf.c \
		../filetype/file/src/readelf.c \
		../filetype/file/src/seccomp.c \
		../filetype/file/src/softmagic.c \
		../filetype/file/src/strcasestr.c \
		../filetype/file/src/strlcat.c \
		../filetype/file/src/strlcpy.c \
		../filetype/file/src/vasprintf.c \
		../filetype/pcre2/src/pcre2_auto_possess.c \
		../filetype/pcre2/src/pcre2_compile.c \
		../filetype/pcre2/src/pcre2_config.c \
		../filetype/pcre2/src/pcre2_context.c \
		../filetype/pcre2/src/pcre2_convert.c \
		../filetype/pcre2/src/pcre2_dfa_match.c \
		../filetype/pcre2/src/pcre2_error.c \
		../filetype/pcre2/src/pcre2_find_bracket.c \
		../filetype/pcre2/src/pcre2_fuzzsupport.c \
		../filetype/pcre2/src/pcre2_jit_compile.c \
		../filetype/pcre2/src/pcre2_maketables.c \
		../filetype/pcre2/src/pcre2_match.c \
		../filetype/pcre2/src/pcre2_match_data.c \
		../filetype/pcre2/src/pcre2_newline.c \
		../filetype/pcre2/src/pcre2_ord2utf.c \
		../filetype/pcre2/src/pcre2_pattern_info.c \
		../filetype/pcre2/src/pcre2_serialize.c \
		../filetype/pcre2/src/pcre2_string_utils.c \
		../filetype/pcre2/src/pcre2_study.c \
		../filetype/pcre2/src/pcre2_substitute.c \
		../filetype/pcre2/src/pcre2_substring.c \
		../filetype/pcre2/src/pcre2_tables.c \
		../filetype/pcre2/src/pcre2_ucd.c \
		../filetype/pcre2/src/pcre2_valid_utf.c \
		../filetype/pcre2/src/pcre2_xclass.c \
		../filetype/pcre2/src/pcre2posix.c
QMAKE_TARGET  = filetype
DESTDIR       = ../filetype/_bin/
TARGET        = libfiletype.a


first: all
####### Build rules

staticlib: ../filetype/_bin/$(TARGET)

../filetype/_bin/libfiletype.a:  $(OBJECTS) $(OBJCOMP) 
	@test -d ../filetype/_bin/ || mkdir -p ../filetype/_bin/
	-$(DEL_FILE) ../filetype/_bin/$(TARGET)
	$(AR) $(DESTDIR)$(TARGET) $(OBJECTS)


Makefile: ../filetype/libfiletype.pro /usr/lib/qt/mkspecs/linux-g++/qmake.conf /usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/sanitize.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_Attica.pri \
		/usr/lib/qt/mkspecs/modules/qt_BluezQt.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivities.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivitiesStats.pri \
		/usr/lib/qt/mkspecs/modules/qt_KArchive.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuth.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuthCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCMUtils.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCrash.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDeclarative.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDESu.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDNSSD.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDSoapClient.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDSoapServer.pri \
		/usr/lib/qt/mkspecs/modules/qt_KEmoticons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KFileMetaData.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KHolidays.pri \
		/usr/lib/qt/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIdleTime.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_Kirigami2.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemModels.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuff.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuffCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifyConfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib/qt/mkspecs/modules/qt_KParts.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPeople.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPeopleWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPty.pri \
		/usr/lib/qt/mkspecs/modules/qt_KRunner.pri \
		/usr/lib/qt/mkspecs/modules/qt_KService.pri \
		/usr/lib/qt/mkspecs/modules/qt_KSyntaxHighlighting.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextEditor.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KUnitConversion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWallet.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandClient.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandServer.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdf.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdf_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_phonon4qt5.pri \
		/usr/lib/qt/mkspecs/modules/qt_Prison.pri \
		/usr/lib/qt/mkspecs/modules/qt_QuickAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_Solid.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri \
		/usr/lib/qt/mkspecs/modules/qt_Syndication.pri \
		/usr/lib/qt/mkspecs/modules/qt_ThreadWeaver.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/toolchain.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/link_ltcg.prf \
		/usr/lib/qt/mkspecs/features/ltcg.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qmake_use.prf \
		/usr/lib/qt/mkspecs/features/file_copies.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		../filetype/libfiletype.pro
	$(QMAKE) -o Makefile ../filetype/libfiletype.pro
/usr/lib/qt/mkspecs/features/spec_pre.prf:
/usr/lib/qt/mkspecs/common/unix.conf:
/usr/lib/qt/mkspecs/common/linux.conf:
/usr/lib/qt/mkspecs/common/sanitize.conf:
/usr/lib/qt/mkspecs/common/gcc-base.conf:
/usr/lib/qt/mkspecs/common/gcc-base-unix.conf:
/usr/lib/qt/mkspecs/common/g++-base.conf:
/usr/lib/qt/mkspecs/common/g++-unix.conf:
/usr/lib/qt/mkspecs/qconfig.pri:
/usr/lib/qt/mkspecs/modules/qt_Attica.pri:
/usr/lib/qt/mkspecs/modules/qt_BluezQt.pri:
/usr/lib/qt/mkspecs/modules/qt_KActivities.pri:
/usr/lib/qt/mkspecs/modules/qt_KActivitiesStats.pri:
/usr/lib/qt/mkspecs/modules/qt_KArchive.pri:
/usr/lib/qt/mkspecs/modules/qt_KAuth.pri:
/usr/lib/qt/mkspecs/modules/qt_KAuthCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri:
/usr/lib/qt/mkspecs/modules/qt_KCMUtils.pri:
/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri:
/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KCrash.pri:
/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KDeclarative.pri:
/usr/lib/qt/mkspecs/modules/qt_KDESu.pri:
/usr/lib/qt/mkspecs/modules/qt_KDNSSD.pri:
/usr/lib/qt/mkspecs/modules/qt_KDSoapClient.pri:
/usr/lib/qt/mkspecs/modules/qt_KDSoapServer.pri:
/usr/lib/qt/mkspecs/modules/qt_KEmoticons.pri:
/usr/lib/qt/mkspecs/modules/qt_KFileMetaData.pri:
/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri:
/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KHolidays.pri:
/usr/lib/qt/mkspecs/modules/qt_KI18n.pri:
/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri:
/usr/lib/qt/mkspecs/modules/qt_KIdleTime.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_Kirigami2.pri:
/usr/lib/qt/mkspecs/modules/qt_KItemModels.pri:
/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri:
/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KNewStuff.pri:
/usr/lib/qt/mkspecs/modules/qt_KNewStuffCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri:
/usr/lib/qt/mkspecs/modules/qt_KNotifyConfig.pri:
/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri:
/usr/lib/qt/mkspecs/modules/qt_KParts.pri:
/usr/lib/qt/mkspecs/modules/qt_KPeople.pri:
/usr/lib/qt/mkspecs/modules/qt_KPeopleWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KPty.pri:
/usr/lib/qt/mkspecs/modules/qt_KRunner.pri:
/usr/lib/qt/mkspecs/modules/qt_KService.pri:
/usr/lib/qt/mkspecs/modules/qt_KSyntaxHighlighting.pri:
/usr/lib/qt/mkspecs/modules/qt_KTextEditor.pri:
/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KUnitConversion.pri:
/usr/lib/qt/mkspecs/modules/qt_KWallet.pri:
/usr/lib/qt/mkspecs/modules/qt_KWaylandClient.pri:
/usr/lib/qt/mkspecs/modules/qt_KWaylandServer.pri:
/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri:
/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_help.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_location.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_pdf.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_pdf_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webengine.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webengine_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/qt/mkspecs/modules/qt_phonon4qt5.pri:
/usr/lib/qt/mkspecs/modules/qt_Prison.pri:
/usr/lib/qt/mkspecs/modules/qt_QuickAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_Solid.pri:
/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri:
/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri:
/usr/lib/qt/mkspecs/modules/qt_Syndication.pri:
/usr/lib/qt/mkspecs/modules/qt_ThreadWeaver.pri:
/usr/lib/qt/mkspecs/features/qt_functions.prf:
/usr/lib/qt/mkspecs/features/qt_config.prf:
/usr/lib/qt/mkspecs/linux-g++/qmake.conf:
/usr/lib/qt/mkspecs/features/spec_post.prf:
/usr/lib/qt/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt/mkspecs/features/toolchain.prf:
/usr/lib/qt/mkspecs/features/default_pre.prf:
/usr/lib/qt/mkspecs/features/resolve_config.prf:
/usr/lib/qt/mkspecs/features/default_post.prf:
/usr/lib/qt/mkspecs/features/link_ltcg.prf:
/usr/lib/qt/mkspecs/features/ltcg.prf:
/usr/lib/qt/mkspecs/features/warn_on.prf:
/usr/lib/qt/mkspecs/features/qmake_use.prf:
/usr/lib/qt/mkspecs/features/file_copies.prf:
/usr/lib/qt/mkspecs/features/testcase_targets.prf:
/usr/lib/qt/mkspecs/features/exceptions.prf:
/usr/lib/qt/mkspecs/features/yacc.prf:
/usr/lib/qt/mkspecs/features/lex.prf:
../filetype/libfiletype.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile ../filetype/libfiletype.pro

qmake_all: FORCE


all: Makefile ../filetype/_bin/libfiletype.a

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) ../filetype/_bin/$(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

benchmark: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

apprentice.o: ../filetype/file/src/apprentice.c ../filetype/file/src/file.h \
		../filetype/misc/config.h \
		../filetype/misc/file_config.h \
		../filetype/misc/pcre2_config.h \
		../filetype/misc/magic.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o apprentice.o ../filetype/file/src/apprentice.c

apptype.o: ../filetype/file/src/apptype.c ../filetype/file/src/file.h \
		../filetype/misc/config.h \
		../filetype/misc/file_config.h \
		../filetype/misc/pcre2_config.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o apptype.o ../filetype/file/src/apptype.c

ascmagic.o: ../filetype/file/src/ascmagic.c ../filetype/file/src/file.h \
		../filetype/misc/config.h \
		../filetype/misc/file_config.h \
		../filetype/misc/pcre2_config.h \
		../filetype/misc/magic.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ascmagic.o ../filetype/file/src/ascmagic.c

asctime_r.o: ../filetype/file/src/asctime_r.c ../filetype/file/src/file.h \
		../filetype/misc/config.h \
		../filetype/misc/file_config.h \
		../filetype/misc/pcre2_config.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o asctime_r.o ../filetype/file/src/asctime_r.c

asprintf.o: ../filetype/file/src/asprintf.c ../filetype/file/src/file.h \
		../filetype/misc/config.h \
		../filetype/misc/file_config.h \
		../filetype/misc/pcre2_config.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o asprintf.o ../filetype/file/src/asprintf.c

buffer.o: ../filetype/file/src/buffer.c ../filetype/file/src/file.h \
		../filetype/misc/config.h \
		../filetype/misc/file_config.h \
		../filetype/misc/pcre2_config.h \
		../filetype/misc/magic.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o buffer.o ../filetype/file/src/buffer.c

cdf.o: ../filetype/file/src/cdf.c ../filetype/file/src/file.h \
		../filetype/misc/config.h \
		../filetype/misc/file_config.h \
		../filetype/misc/pcre2_config.h \
		../filetype/file/src/cdf.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o cdf.o ../filetype/file/src/cdf.c

cdf_time.o: ../filetype/file/src/cdf_time.c ../filetype/file/src/file.h \
		../filetype/misc/config.h \
		../filetype/misc/file_config.h \
		../filetype/misc/pcre2_config.h \
		../filetype/file/src/cdf.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o cdf_time.o ../filetype/file/src/cdf_time.c

compress.o: ../filetype/file/src/compress.c ../filetype/file/src/file.h \
		../filetype/misc/config.h \
		../filetype/misc/file_config.h \
		../filetype/misc/pcre2_config.h \
		../filetype/misc/magic.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o compress.o ../filetype/file/src/compress.c

ctime_r.o: ../filetype/file/src/ctime_r.c ../filetype/file/src/file.h \
		../filetype/misc/config.h \
		../filetype/misc/file_config.h \
		../filetype/misc/pcre2_config.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ctime_r.o ../filetype/file/src/ctime_r.c

der.o: ../filetype/file/src/der.c ../filetype/file/src/file.h \
		../filetype/misc/config.h \
		../filetype/misc/file_config.h \
		../filetype/misc/pcre2_config.h \
		../filetype/misc/magic.h \
		../filetype/file/src/der.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o der.o ../filetype/file/src/der.c

dprintf.o: ../filetype/file/src/dprintf.c ../filetype/file/src/file.h \
		../filetype/misc/config.h \
		../filetype/misc/file_config.h \
		../filetype/misc/pcre2_config.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o dprintf.o ../filetype/file/src/dprintf.c

encoding.o: ../filetype/file/src/encoding.c ../filetype/file/src/file.h \
		../filetype/misc/config.h \
		../filetype/misc/file_config.h \
		../filetype/misc/pcre2_config.h \
		../filetype/misc/magic.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o encoding.o ../filetype/file/src/encoding.c

fmtcheck.o: ../filetype/file/src/fmtcheck.c ../filetype/file/src/file.h \
		../filetype/misc/config.h \
		../filetype/misc/file_config.h \
		../filetype/misc/pcre2_config.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o fmtcheck.o ../filetype/file/src/fmtcheck.c

fsmagic.o: ../filetype/file/src/fsmagic.c ../filetype/file/src/file.h \
		../filetype/misc/config.h \
		../filetype/misc/file_config.h \
		../filetype/misc/pcre2_config.h \
		../filetype/misc/magic.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o fsmagic.o ../filetype/file/src/fsmagic.c

funcs.o: ../filetype/file/src/funcs.c ../filetype/file/src/file.h \
		../filetype/misc/config.h \
		../filetype/misc/file_config.h \
		../filetype/misc/pcre2_config.h \
		../filetype/misc/magic.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o funcs.o ../filetype/file/src/funcs.c

getline.o: ../filetype/file/src/getline.c ../filetype/file/src/file.h \
		../filetype/misc/config.h \
		../filetype/misc/file_config.h \
		../filetype/misc/pcre2_config.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o getline.o ../filetype/file/src/getline.c

gmtime_r.o: ../filetype/file/src/gmtime_r.c ../filetype/file/src/file.h \
		../filetype/misc/config.h \
		../filetype/misc/file_config.h \
		../filetype/misc/pcre2_config.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o gmtime_r.o ../filetype/file/src/gmtime_r.c

is_csv.o: ../filetype/file/src/is_csv.c ../filetype/file/src/file.h \
		../filetype/misc/config.h \
		../filetype/misc/file_config.h \
		../filetype/misc/pcre2_config.h \
		../filetype/misc/magic.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o is_csv.o ../filetype/file/src/is_csv.c

is_json.o: ../filetype/file/src/is_json.c ../filetype/file/src/file.h \
		../filetype/misc/config.h \
		../filetype/misc/file_config.h \
		../filetype/misc/pcre2_config.h \
		../filetype/misc/magic.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o is_json.o ../filetype/file/src/is_json.c

is_simh.o: ../filetype/file/src/is_simh.c ../filetype/file/src/file.h \
		../filetype/misc/config.h \
		../filetype/misc/file_config.h \
		../filetype/misc/pcre2_config.h \
		../filetype/misc/magic.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o is_simh.o ../filetype/file/src/is_simh.c

is_tar.o: ../filetype/file/src/is_tar.c ../filetype/file/src/file.h \
		../filetype/misc/config.h \
		../filetype/misc/file_config.h \
		../filetype/misc/pcre2_config.h \
		../filetype/misc/magic.h \
		../filetype/file/src/tar.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o is_tar.o ../filetype/file/src/is_tar.c

localtime_r.o: ../filetype/file/src/localtime_r.c ../filetype/file/src/file.h \
		../filetype/misc/config.h \
		../filetype/misc/file_config.h \
		../filetype/misc/pcre2_config.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o localtime_r.o ../filetype/file/src/localtime_r.c

magic.o: ../filetype/file/src/magic.c ../filetype/file/src/file.h \
		../filetype/misc/config.h \
		../filetype/misc/file_config.h \
		../filetype/misc/pcre2_config.h \
		../filetype/misc/magic.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o magic.o ../filetype/file/src/magic.c

pread.o: ../filetype/file/src/pread.c ../filetype/file/src/file.h \
		../filetype/misc/config.h \
		../filetype/misc/file_config.h \
		../filetype/misc/pcre2_config.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pread.o ../filetype/file/src/pread.c

print.o: ../filetype/file/src/print.c ../filetype/file/src/file.h \
		../filetype/misc/config.h \
		../filetype/misc/file_config.h \
		../filetype/misc/pcre2_config.h \
		../filetype/file/src/cdf.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o print.o ../filetype/file/src/print.c

readcdf.o: ../filetype/file/src/readcdf.c ../filetype/file/src/file.h \
		../filetype/misc/config.h \
		../filetype/misc/file_config.h \
		../filetype/misc/pcre2_config.h \
		../filetype/file/src/cdf.h \
		../filetype/misc/magic.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o readcdf.o ../filetype/file/src/readcdf.c

readelf.o: ../filetype/file/src/readelf.c ../filetype/file/src/file.h \
		../filetype/misc/config.h \
		../filetype/misc/file_config.h \
		../filetype/misc/pcre2_config.h \
		../filetype/file/src/readelf.h \
		../filetype/misc/magic.h \
		../filetype/file/src/elfclass.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o readelf.o ../filetype/file/src/readelf.c

seccomp.o: ../filetype/file/src/seccomp.c ../filetype/file/src/file.h \
		../filetype/misc/config.h \
		../filetype/misc/file_config.h \
		../filetype/misc/pcre2_config.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o seccomp.o ../filetype/file/src/seccomp.c

softmagic.o: ../filetype/file/src/softmagic.c ../filetype/file/src/file.h \
		../filetype/misc/config.h \
		../filetype/misc/file_config.h \
		../filetype/misc/pcre2_config.h \
		../filetype/misc/magic.h \
		../filetype/file/src/der.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o softmagic.o ../filetype/file/src/softmagic.c

strcasestr.o: ../filetype/file/src/strcasestr.c ../filetype/file/src/file.h \
		../filetype/misc/config.h \
		../filetype/misc/file_config.h \
		../filetype/misc/pcre2_config.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o strcasestr.o ../filetype/file/src/strcasestr.c

strlcat.o: ../filetype/file/src/strlcat.c ../filetype/file/src/file.h \
		../filetype/misc/config.h \
		../filetype/misc/file_config.h \
		../filetype/misc/pcre2_config.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o strlcat.o ../filetype/file/src/strlcat.c

strlcpy.o: ../filetype/file/src/strlcpy.c ../filetype/file/src/file.h \
		../filetype/misc/config.h \
		../filetype/misc/file_config.h \
		../filetype/misc/pcre2_config.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o strlcpy.o ../filetype/file/src/strlcpy.c

vasprintf.o: ../filetype/file/src/vasprintf.c ../filetype/file/src/file.h \
		../filetype/misc/config.h \
		../filetype/misc/file_config.h \
		../filetype/misc/pcre2_config.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o vasprintf.o ../filetype/file/src/vasprintf.c

pcre2_auto_possess.o: ../filetype/pcre2/src/pcre2_auto_possess.c ../filetype/pcre2/src/pcre2_internal.h \
		../filetype/pcre2/src/config.h \
		../filetype/pcre2/src/pcre2.h \
		../filetype/pcre2/src/pcre2_ucp.h \
		../filetype/pcre2/src/pcre2_intmodedep.h \
		../filetype/pcre2/src/pcre2_util.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pcre2_auto_possess.o ../filetype/pcre2/src/pcre2_auto_possess.c

pcre2_compile.o: ../filetype/pcre2/src/pcre2_compile.c ../filetype/pcre2/src/pcre2_compile.h \
		../filetype/pcre2/src/pcre2_internal.h \
		../filetype/pcre2/src/config.h \
		../filetype/pcre2/src/pcre2.h \
		../filetype/pcre2/src/pcre2_ucp.h \
		../filetype/pcre2/src/pcre2_intmodedep.h \
		../filetype/pcre2/src/pcre2_util.h \
		../filetype/pcre2/src/pcre2_printint_inc.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pcre2_compile.o ../filetype/pcre2/src/pcre2_compile.c

pcre2_config.o: ../filetype/pcre2/src/pcre2_config.c ../filetype/pcre2/src/pcre2_internal.h \
		../filetype/pcre2/src/config.h \
		../filetype/pcre2/src/pcre2.h \
		../filetype/pcre2/src/pcre2_ucp.h \
		../filetype/pcre2/src/pcre2_intmodedep.h \
		../filetype/pcre2/src/pcre2_util.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pcre2_config.o ../filetype/pcre2/src/pcre2_config.c

pcre2_context.o: ../filetype/pcre2/src/pcre2_context.c ../filetype/pcre2/src/pcre2_internal.h \
		../filetype/pcre2/src/config.h \
		../filetype/pcre2/src/pcre2.h \
		../filetype/pcre2/src/pcre2_ucp.h \
		../filetype/pcre2/src/pcre2_intmodedep.h \
		../filetype/pcre2/src/pcre2_util.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pcre2_context.o ../filetype/pcre2/src/pcre2_context.c

pcre2_convert.o: ../filetype/pcre2/src/pcre2_convert.c ../filetype/pcre2/src/pcre2_internal.h \
		../filetype/pcre2/src/config.h \
		../filetype/pcre2/src/pcre2.h \
		../filetype/pcre2/src/pcre2_ucp.h \
		../filetype/pcre2/src/pcre2_intmodedep.h \
		../filetype/pcre2/src/pcre2_util.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pcre2_convert.o ../filetype/pcre2/src/pcre2_convert.c

pcre2_dfa_match.o: ../filetype/pcre2/src/pcre2_dfa_match.c ../filetype/pcre2/src/pcre2_internal.h \
		../filetype/pcre2/src/config.h \
		../filetype/pcre2/src/pcre2.h \
		../filetype/pcre2/src/pcre2_ucp.h \
		../filetype/pcre2/src/pcre2_intmodedep.h \
		../filetype/pcre2/src/pcre2_util.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pcre2_dfa_match.o ../filetype/pcre2/src/pcre2_dfa_match.c

pcre2_error.o: ../filetype/pcre2/src/pcre2_error.c ../filetype/pcre2/src/pcre2_internal.h \
		../filetype/pcre2/src/config.h \
		../filetype/pcre2/src/pcre2.h \
		../filetype/pcre2/src/pcre2_ucp.h \
		../filetype/pcre2/src/pcre2_intmodedep.h \
		../filetype/pcre2/src/pcre2_util.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pcre2_error.o ../filetype/pcre2/src/pcre2_error.c

pcre2_find_bracket.o: ../filetype/pcre2/src/pcre2_find_bracket.c ../filetype/pcre2/src/pcre2_internal.h \
		../filetype/pcre2/src/config.h \
		../filetype/pcre2/src/pcre2.h \
		../filetype/pcre2/src/pcre2_ucp.h \
		../filetype/pcre2/src/pcre2_intmodedep.h \
		../filetype/pcre2/src/pcre2_util.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pcre2_find_bracket.o ../filetype/pcre2/src/pcre2_find_bracket.c

pcre2_fuzzsupport.o: ../filetype/pcre2/src/pcre2_fuzzsupport.c ../filetype/pcre2/src/pcre2_internal.h \
		../filetype/pcre2/src/config.h \
		../filetype/pcre2/src/pcre2.h \
		../filetype/pcre2/src/pcre2_ucp.h \
		../filetype/pcre2/src/pcre2_intmodedep.h \
		../filetype/pcre2/src/pcre2_util.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pcre2_fuzzsupport.o ../filetype/pcre2/src/pcre2_fuzzsupport.c

pcre2_jit_compile.o: ../filetype/pcre2/src/pcre2_jit_compile.c ../filetype/pcre2/src/pcre2_internal.h \
		../filetype/pcre2/src/config.h \
		../filetype/pcre2/src/pcre2.h \
		../filetype/pcre2/src/pcre2_ucp.h \
		../filetype/pcre2/src/pcre2_intmodedep.h \
		../filetype/pcre2/src/pcre2_util.h \
		../filetype/pcre2/src/pcre2_jit_simd_inc.h \
		../filetype/pcre2/src/pcre2_jit_neon_inc.h \
		../filetype/pcre2/src/pcre2_jit_char_inc.h \
		../filetype/pcre2/src/pcre2_jit_match_inc.h \
		../filetype/pcre2/src/pcre2_jit_misc_inc.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pcre2_jit_compile.o ../filetype/pcre2/src/pcre2_jit_compile.c

pcre2_maketables.o: ../filetype/pcre2/src/pcre2_maketables.c ../filetype/pcre2/src/pcre2_internal.h \
		../filetype/pcre2/src/config.h \
		../filetype/pcre2/src/pcre2.h \
		../filetype/pcre2/src/pcre2_ucp.h \
		../filetype/pcre2/src/pcre2_intmodedep.h \
		../filetype/pcre2/src/pcre2_util.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pcre2_maketables.o ../filetype/pcre2/src/pcre2_maketables.c

pcre2_match.o: ../filetype/pcre2/src/pcre2_match.c ../filetype/pcre2/src/pcre2_internal.h \
		../filetype/pcre2/src/config.h \
		../filetype/pcre2/src/pcre2.h \
		../filetype/pcre2/src/pcre2_ucp.h \
		../filetype/pcre2/src/pcre2_intmodedep.h \
		../filetype/pcre2/src/pcre2_util.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pcre2_match.o ../filetype/pcre2/src/pcre2_match.c

pcre2_match_data.o: ../filetype/pcre2/src/pcre2_match_data.c ../filetype/pcre2/src/pcre2_internal.h \
		../filetype/pcre2/src/config.h \
		../filetype/pcre2/src/pcre2.h \
		../filetype/pcre2/src/pcre2_ucp.h \
		../filetype/pcre2/src/pcre2_intmodedep.h \
		../filetype/pcre2/src/pcre2_util.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pcre2_match_data.o ../filetype/pcre2/src/pcre2_match_data.c

pcre2_newline.o: ../filetype/pcre2/src/pcre2_newline.c ../filetype/pcre2/src/pcre2_internal.h \
		../filetype/pcre2/src/config.h \
		../filetype/pcre2/src/pcre2.h \
		../filetype/pcre2/src/pcre2_ucp.h \
		../filetype/pcre2/src/pcre2_intmodedep.h \
		../filetype/pcre2/src/pcre2_util.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pcre2_newline.o ../filetype/pcre2/src/pcre2_newline.c

pcre2_ord2utf.o: ../filetype/pcre2/src/pcre2_ord2utf.c ../filetype/pcre2/src/pcre2_internal.h \
		../filetype/pcre2/src/config.h \
		../filetype/pcre2/src/pcre2.h \
		../filetype/pcre2/src/pcre2_ucp.h \
		../filetype/pcre2/src/pcre2_intmodedep.h \
		../filetype/pcre2/src/pcre2_util.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pcre2_ord2utf.o ../filetype/pcre2/src/pcre2_ord2utf.c

pcre2_pattern_info.o: ../filetype/pcre2/src/pcre2_pattern_info.c ../filetype/pcre2/src/pcre2_internal.h \
		../filetype/pcre2/src/config.h \
		../filetype/pcre2/src/pcre2.h \
		../filetype/pcre2/src/pcre2_ucp.h \
		../filetype/pcre2/src/pcre2_intmodedep.h \
		../filetype/pcre2/src/pcre2_util.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pcre2_pattern_info.o ../filetype/pcre2/src/pcre2_pattern_info.c

pcre2_serialize.o: ../filetype/pcre2/src/pcre2_serialize.c ../filetype/pcre2/src/pcre2_internal.h \
		../filetype/pcre2/src/config.h \
		../filetype/pcre2/src/pcre2.h \
		../filetype/pcre2/src/pcre2_ucp.h \
		../filetype/pcre2/src/pcre2_intmodedep.h \
		../filetype/pcre2/src/pcre2_util.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pcre2_serialize.o ../filetype/pcre2/src/pcre2_serialize.c

pcre2_string_utils.o: ../filetype/pcre2/src/pcre2_string_utils.c ../filetype/pcre2/src/pcre2_internal.h \
		../filetype/pcre2/src/config.h \
		../filetype/pcre2/src/pcre2.h \
		../filetype/pcre2/src/pcre2_ucp.h \
		../filetype/pcre2/src/pcre2_intmodedep.h \
		../filetype/pcre2/src/pcre2_util.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pcre2_string_utils.o ../filetype/pcre2/src/pcre2_string_utils.c

pcre2_study.o: ../filetype/pcre2/src/pcre2_study.c ../filetype/pcre2/src/pcre2_internal.h \
		../filetype/pcre2/src/config.h \
		../filetype/pcre2/src/pcre2.h \
		../filetype/pcre2/src/pcre2_ucp.h \
		../filetype/pcre2/src/pcre2_intmodedep.h \
		../filetype/pcre2/src/pcre2_util.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pcre2_study.o ../filetype/pcre2/src/pcre2_study.c

pcre2_substitute.o: ../filetype/pcre2/src/pcre2_substitute.c ../filetype/pcre2/src/pcre2_internal.h \
		../filetype/pcre2/src/config.h \
		../filetype/pcre2/src/pcre2.h \
		../filetype/pcre2/src/pcre2_ucp.h \
		../filetype/pcre2/src/pcre2_intmodedep.h \
		../filetype/pcre2/src/pcre2_util.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pcre2_substitute.o ../filetype/pcre2/src/pcre2_substitute.c

pcre2_substring.o: ../filetype/pcre2/src/pcre2_substring.c ../filetype/pcre2/src/pcre2_internal.h \
		../filetype/pcre2/src/config.h \
		../filetype/pcre2/src/pcre2.h \
		../filetype/pcre2/src/pcre2_ucp.h \
		../filetype/pcre2/src/pcre2_intmodedep.h \
		../filetype/pcre2/src/pcre2_util.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pcre2_substring.o ../filetype/pcre2/src/pcre2_substring.c

pcre2_tables.o: ../filetype/pcre2/src/pcre2_tables.c ../filetype/pcre2/src/pcre2_internal.h \
		../filetype/pcre2/src/config.h \
		../filetype/pcre2/src/pcre2.h \
		../filetype/pcre2/src/pcre2_ucp.h \
		../filetype/pcre2/src/pcre2_intmodedep.h \
		../filetype/pcre2/src/pcre2_util.h \
		../filetype/pcre2/src/pcre2_ucptables_inc.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pcre2_tables.o ../filetype/pcre2/src/pcre2_tables.c

pcre2_ucd.o: ../filetype/pcre2/src/pcre2_ucd.c ../filetype/pcre2/src/pcre2_internal.h \
		../filetype/pcre2/src/config.h \
		../filetype/pcre2/src/pcre2.h \
		../filetype/pcre2/src/pcre2_ucp.h \
		../filetype/pcre2/src/pcre2_intmodedep.h \
		../filetype/pcre2/src/pcre2_util.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pcre2_ucd.o ../filetype/pcre2/src/pcre2_ucd.c

pcre2_valid_utf.o: ../filetype/pcre2/src/pcre2_valid_utf.c ../filetype/pcre2/src/pcre2_internal.h \
		../filetype/pcre2/src/config.h \
		../filetype/pcre2/src/pcre2.h \
		../filetype/pcre2/src/pcre2_ucp.h \
		../filetype/pcre2/src/pcre2_intmodedep.h \
		../filetype/pcre2/src/pcre2_util.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pcre2_valid_utf.o ../filetype/pcre2/src/pcre2_valid_utf.c

pcre2_xclass.o: ../filetype/pcre2/src/pcre2_xclass.c ../filetype/pcre2/src/pcre2_internal.h \
		../filetype/pcre2/src/config.h \
		../filetype/pcre2/src/pcre2.h \
		../filetype/pcre2/src/pcre2_ucp.h \
		../filetype/pcre2/src/pcre2_intmodedep.h \
		../filetype/pcre2/src/pcre2_util.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pcre2_xclass.o ../filetype/pcre2/src/pcre2_xclass.c

pcre2posix.o: ../filetype/pcre2/src/pcre2posix.c ../filetype/pcre2/src/config.h \
		../filetype/pcre2/src/pcre2.h \
		../filetype/pcre2/src/pcre2posix.h \
		../filetype/pcre2/src/pcre2_util.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pcre2posix.o ../filetype/pcre2/src/pcre2posix.c

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

