/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace MeCab {

using System;
using System.Runtime.InteropServices;

public class MeCab {
  public static readonly int MECAB_NOR_NODE = MeCabPINVOKE.MECAB_NOR_NODE_get();
  public static readonly int MECAB_UNK_NODE = MeCabPINVOKE.MECAB_UNK_NODE_get();
  public static readonly int MECAB_BOS_NODE = MeCabPINVOKE.MECAB_BOS_NODE_get();
  public static readonly int MECAB_EOS_NODE = MeCabPINVOKE.MECAB_EOS_NODE_get();
  public static readonly int MECAB_EON_NODE = MeCabPINVOKE.MECAB_EON_NODE_get();

  public static readonly int MECAB_SYS_DIC = MeCabPINVOKE.MECAB_SYS_DIC_get();
  public static readonly int MECAB_USR_DIC = MeCabPINVOKE.MECAB_USR_DIC_get();
  public static readonly int MECAB_UNK_DIC = MeCabPINVOKE.MECAB_UNK_DIC_get();

  public static readonly int MECAB_ONE_BEST = MeCabPINVOKE.MECAB_ONE_BEST_get();
  public static readonly int MECAB_NBEST = MeCabPINVOKE.MECAB_NBEST_get();
  public static readonly int MECAB_PARTIAL = MeCabPINVOKE.MECAB_PARTIAL_get();
  public static readonly int MECAB_MARGINAL_PROB = MeCabPINVOKE.MECAB_MARGINAL_PROB_get();
  public static readonly int MECAB_ALTERNATIVE = MeCabPINVOKE.MECAB_ALTERNATIVE_get();
  public static readonly int MECAB_ALL_MORPHS = MeCabPINVOKE.MECAB_ALL_MORPHS_get();
  public static readonly int MECAB_ALLOCATE_SENTENCE = MeCabPINVOKE.MECAB_ALLOCATE_SENTENCE_get();

  public static readonly int MECAB_ANY_BOUNDARY = MeCabPINVOKE.MECAB_ANY_BOUNDARY_get();
  public static readonly int MECAB_TOKEN_BOUNDARY = MeCabPINVOKE.MECAB_TOKEN_BOUNDARY_get();
  public static readonly int MECAB_INSIDE_TOKEN = MeCabPINVOKE.MECAB_INSIDE_TOKEN_get();

  public static readonly string VERSION = MeCabPINVOKE.VERSION_get();
}

}
