#!/bin/sh

prefix=/usr/local
exec_prefix=${prefix}
exec_prefix_set=no

usage()
{
    cat <<EOF
Usage: mecab-config [OPTIONS]

Options:
  [--cxx]
  [--prefix[=DIR]]
  [--exec-prefix[=DIR]]
  [--libs]
  [--cflags]
  [--dicdir]
  [--libexecdir]
  [--sysconfdir]
  [--libs-only-L]
  [--libs-only-l]
  [--inc-dir]
  [--help]
  [--version]
EOF

    exit $1
}

if test $# -eq 0; then
    usage 1
fi

cflags=false
libs=false

while test $# -gt 0; do
    case "$1" in
    -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
    *) optarg= ;;
    esac

    case "$1" in
    --cxx)
       echo g++
       ;;
       
    --cc)
       echo gcc
       ;;
       
    --prefix=*)
	prefix=$optarg
        if test $exec_prefix_set = no ; then
          exec_prefix=$optarg
        fi
	;;

    --prefix)
	echo $prefix
	;;

    --exec-prefix=*)
	exec_prefix=$optarg
	exec_prefix_set=yes
	;;

    --exec-prefix)
	echo $exec_prefix
	;;

    --version)
	echo 0.996
	exit 0
	;;

    --help)
	usage 0
	;;

    --cflags)
        if test ${prefix}/include != /usr/include ; then
          includes=-I${prefix}/include
        fi
        echo $includes
       	;;

    --libs)
       	echo -L${exec_prefix}/lib -lmecab -lstdc++
       	;;

    --dicdir)
       	echo ${exec_prefix}/lib/mecab/dic
       	;;
	
    --inc-dir)
        echo ${prefix}/include
	;;
    
    --libs-only-L)
        echo ${exec_prefix}/lib
	;;
	
    --libs-only-l)
        echo -lmecab -lstdc++ | sed s/-l//g;
	;;

    --libexecdir)
       	echo /usr/local/libexec/mecab
       	;;
	
    --sysconfdir)
       	echo ${prefix}/etc
       	;;

    *)
	usage
	exit 1
	;;
    esac
    shift
done

exit 0
