/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.chasen.mecab;

public class DictionaryInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public DictionaryInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(DictionaryInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MeCabJNI.delete_DictionaryInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public String getFilename() {
    return MeCabJNI.DictionaryInfo_filename_get(swigCPtr, this);
  }

  public String getCharset() {
    return MeCabJNI.DictionaryInfo_charset_get(swigCPtr, this);
  }

  public long getSize() {
    return MeCabJNI.DictionaryInfo_size_get(swigCPtr, this);
  }

  public int getType() {
    return MeCabJNI.DictionaryInfo_type_get(swigCPtr, this);
  }

  public long getLsize() {
    return MeCabJNI.DictionaryInfo_lsize_get(swigCPtr, this);
  }

  public long getRsize() {
    return MeCabJNI.DictionaryInfo_rsize_get(swigCPtr, this);
  }

  public int getVersion() {
    return MeCabJNI.DictionaryInfo_version_get(swigCPtr, this);
  }

  public DictionaryInfo getNext() {
    long cPtr = MeCabJNI.DictionaryInfo_next_get(swigCPtr, this);
    return (cPtr == 0) ? null : new DictionaryInfo(cPtr, false);
  }

  public DictionaryInfo() {
    this(MeCabJNI.new_DictionaryInfo(), true);
  }

}
