/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.chasen.mecab;

public interface MeCabConstants {
  public final static int MECAB_NOR_NODE = MeCabJNI.MECAB_NOR_NODE_get();
  public final static int MECAB_UNK_NODE = MeCabJNI.MECAB_UNK_NODE_get();
  public final static int MECAB_BOS_NODE = MeCabJNI.MECAB_BOS_NODE_get();
  public final static int MECAB_EOS_NODE = MeCabJNI.MECAB_EOS_NODE_get();
  public final static int MECAB_EON_NODE = MeCabJNI.MECAB_EON_NODE_get();

  public final static int MECAB_SYS_DIC = MeCabJNI.MECAB_SYS_DIC_get();
  public final static int MECAB_USR_DIC = MeCabJNI.MECAB_USR_DIC_get();
  public final static int MECAB_UNK_DIC = MeCabJNI.MECAB_UNK_DIC_get();

  public final static int MECAB_ONE_BEST = MeCabJNI.MECAB_ONE_BEST_get();
  public final static int MECAB_NBEST = MeCabJNI.MECAB_NBEST_get();
  public final static int MECAB_PARTIAL = MeCabJNI.MECAB_PARTIAL_get();
  public final static int MECAB_MARGINAL_PROB = MeCabJNI.MECAB_MARGINAL_PROB_get();
  public final static int MECAB_ALTERNATIVE = MeCabJNI.MECAB_ALTERNATIVE_get();
  public final static int MECAB_ALL_MORPHS = MeCabJNI.MECAB_ALL_MORPHS_get();
  public final static int MECAB_ALLOCATE_SENTENCE = MeCabJNI.MECAB_ALLOCATE_SENTENCE_get();

  public final static int MECAB_ANY_BOUNDARY = MeCabJNI.MECAB_ANY_BOUNDARY_get();
  public final static int MECAB_TOKEN_BOUNDARY = MeCabJNI.MECAB_TOKEN_BOUNDARY_get();
  public final static int MECAB_INSIDE_TOKEN = MeCabJNI.MECAB_INSIDE_TOKEN_get();

  public final static String VERSION = MeCabJNI.VERSION_get();
}
