#include "AboutDialog.h"
#include "ui_AboutDialog.h"
#include "misc.h"

#include <QPainter>

// defined in 'version.c' generated by prepare.rb
extern "C" int copyright_year;
extern "C" char const product_version[];
extern "C" char const source_revision[];

AboutDialog::AboutDialog(QWidget *parent) :
	QDialog(parent),
	ui(new Ui::AboutDialog)
{
	ui->setupUi(this);
	Qt::WindowFlags flags = windowFlags();
	flags &= ~Qt::WindowContextHelpButtonHint;
	setWindowFlags(flags);

	misc::setFixedSize(this);

	pixmap.load(":/image/about.png");

	setWindowTitle(tr("About Guitar"));

	ui->label_title->setText(appVersion());
	ui->label_copyright->setText(QString("Copyright (C) %1 S.Fuchita").arg(copyright_year));
	ui->label_twitter->setText("(@soramimi_jp)");
	QString t = QString("Qt %1").arg(qVersion());
#if defined(_MSC_VER)
	t += QString(", msvc=%1").arg(_MSC_VER);
#elif defined(__clang__)
	t += QString(", clang=%1.%2").arg(__clang_major__).arg(__clang_minor__);
#elif defined(__GNUC__)
	t += QString(", gcc=%1.%2.%3").arg(__GNUC__).arg(__GNUC_MINOR__).arg(__GNUC_PATCHLEVEL__);
#endif
	ui->label_qt->setText(t);
}

AboutDialog::~AboutDialog()
{
	delete ui;
}

void AboutDialog::mouseReleaseEvent(QMouseEvent *)
{
	accept();
}

void AboutDialog::paintEvent(QPaintEvent *event)
{
	QPainter pr(this);
	int w = width();
	int h = height();
	pr.drawPixmap(0, 0, w, h, pixmap);
}

QString AboutDialog::appVersion()
{
	return QString("Guitar, v%1 (%2)").arg(product_version).arg(source_revision);
}
