#############################################################################
# Makefile for building: libfiletype.a
# Generated by qmake (3.1) (Qt 5.15.16)
# Project:  libfiletype.pro
# Template: lib
# Command: /usr/bin/qmake -o Makefile libfiletype.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DHAVE_CONFIG_H=1 -D_SSIZE_T_DEFINED=1 -DPCRE2_CODE_UNIT_WIDTH=8 -DHAVE_MKSTEMP=1
CFLAGS        = -pipe -O2 -fPIC -flto -fno-fat-lto-objects -Wall -Wextra $(DEFINES)
CXXFLAGS      = -pipe -O2 -fPIC -std=gnu++11 -flto -fno-fat-lto-objects -Wall -Wextra $(DEFINES)
INCPATH       = -I. -Imisc -Ifile/src -Ipcre2/src -I/usr/lib/qt/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = filetype1.0.0
DISTDIR = /home/soramimi/develop/filetype/.tmp/filetype1.0.0
AR            = gcc-ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = file/src/apprentice.c \
		file/src/apptype.c \
		file/src/ascmagic.c \
		file/src/asctime_r.c \
		file/src/asprintf.c \
		file/src/buffer.c \
		file/src/cdf.c \
		file/src/cdf_time.c \
		file/src/compress.c \
		file/src/ctime_r.c \
		file/src/der.c \
		file/src/dprintf.c \
		file/src/encoding.c \
		file/src/fmtcheck.c \
		file/src/fsmagic.c \
		file/src/funcs.c \
		file/src/getline.c \
		file/src/gmtime_r.c \
		file/src/is_csv.c \
		file/src/is_json.c \
		file/src/is_simh.c \
		file/src/is_tar.c \
		file/src/localtime_r.c \
		file/src/magic.c \
		file/src/pread.c \
		file/src/print.c \
		file/src/readcdf.c \
		file/src/readelf.c \
		file/src/seccomp.c \
		file/src/softmagic.c \
		file/src/strcasestr.c \
		file/src/strlcat.c \
		file/src/strlcpy.c \
		file/src/vasprintf.c \
		pcre2/src/pcre2_auto_possess.c \
		pcre2/src/pcre2_chartables.c \
		pcre2/src/pcre2_compile.c \
		pcre2/src/pcre2_config.c \
		pcre2/src/pcre2_context.c \
		pcre2/src/pcre2_convert.c \
		pcre2/src/pcre2_dfa_match.c \
		pcre2/src/pcre2_error.c \
		pcre2/src/pcre2_find_bracket.c \
		pcre2/src/pcre2_fuzzsupport.c \
		pcre2/src/pcre2_jit_compile.c \
		pcre2/src/pcre2_maketables.c \
		pcre2/src/pcre2_match.c \
		pcre2/src/pcre2_match_data.c \
		pcre2/src/pcre2_newline.c \
		pcre2/src/pcre2_ord2utf.c \
		pcre2/src/pcre2_pattern_info.c \
		pcre2/src/pcre2_serialize.c \
		pcre2/src/pcre2_string_utils.c \
		pcre2/src/pcre2_study.c \
		pcre2/src/pcre2_substitute.c \
		pcre2/src/pcre2_substring.c \
		pcre2/src/pcre2_tables.c \
		pcre2/src/pcre2_ucd.c \
		pcre2/src/pcre2_valid_utf.c \
		pcre2/src/pcre2_xclass.c \
		pcre2/src/pcre2posix.c 
OBJECTS       = apprentice.o \
		apptype.o \
		ascmagic.o \
		asctime_r.o \
		asprintf.o \
		buffer.o \
		cdf.o \
		cdf_time.o \
		compress.o \
		ctime_r.o \
		der.o \
		dprintf.o \
		encoding.o \
		fmtcheck.o \
		fsmagic.o \
		funcs.o \
		getline.o \
		gmtime_r.o \
		is_csv.o \
		is_json.o \
		is_simh.o \
		is_tar.o \
		localtime_r.o \
		magic.o \
		pread.o \
		print.o \
		readcdf.o \
		readelf.o \
		seccomp.o \
		softmagic.o \
		strcasestr.o \
		strlcat.o \
		strlcpy.o \
		vasprintf.o \
		pcre2_auto_possess.o \
		pcre2_chartables.o \
		pcre2_compile.o \
		pcre2_config.o \
		pcre2_context.o \
		pcre2_convert.o \
		pcre2_dfa_match.o \
		pcre2_error.o \
		pcre2_find_bracket.o \
		pcre2_fuzzsupport.o \
		pcre2_jit_compile.o \
		pcre2_maketables.o \
		pcre2_match.o \
		pcre2_match_data.o \
		pcre2_newline.o \
		pcre2_ord2utf.o \
		pcre2_pattern_info.o \
		pcre2_serialize.o \
		pcre2_string_utils.o \
		pcre2_study.o \
		pcre2_substitute.o \
		pcre2_substring.o \
		pcre2_tables.o \
		pcre2_ucd.o \
		pcre2_valid_utf.o \
		pcre2_xclass.o \
		pcre2posix.o
DIST          = /usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/sanitize.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_Attica.pri \
		/usr/lib/qt/mkspecs/modules/qt_BluezQt.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivities.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivitiesStats.pri \
		/usr/lib/qt/mkspecs/modules/qt_KArchive.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuth.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuthCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCMUtils.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCrash.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDeclarative.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDESu.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDNSSD.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDSoapClient.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDSoapServer.pri \
		/usr/lib/qt/mkspecs/modules/qt_KEmoticons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KFileMetaData.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KHolidays.pri \
		/usr/lib/qt/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIdleTime.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_Kirigami2.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemModels.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuff.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuffCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifyConfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib/qt/mkspecs/modules/qt_KParts.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPeople.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPeopleWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPty.pri \
		/usr/lib/qt/mkspecs/modules/qt_KRunner.pri \
		/usr/lib/qt/mkspecs/modules/qt_KService.pri \
		/usr/lib/qt/mkspecs/modules/qt_KSyntaxHighlighting.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextEditor.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KUnitConversion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWallet.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandClient.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandServer.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdf.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdf_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_phonon4qt5.pri \
		/usr/lib/qt/mkspecs/modules/qt_Prison.pri \
		/usr/lib/qt/mkspecs/modules/qt_QuickAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_Solid.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri \
		/usr/lib/qt/mkspecs/modules/qt_Syndication.pri \
		/usr/lib/qt/mkspecs/modules/qt_ThreadWeaver.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/toolchain.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/link_ltcg.prf \
		/usr/lib/qt/mkspecs/features/ltcg.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qmake_use.prf \
		/usr/lib/qt/mkspecs/features/file_copies.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		libfiletype.pro file/src/cdf.h \
		file/src/der.h \
		file/src/elfclass.h \
		file/src/file.h \
		file/src/file_opts.h \
		file/src/patchlevel.h \
		file/src/readelf.h \
		file/src/tar.h \
		misc/config.h \
		misc/file_config.h \
		misc/pcre2.h \
		misc/pcre2_config.h \
		pcre2/src/pcre2_internal.h \
		pcre2/src/pcre2_intmodedep.h \
		pcre2/src/pcre2_ucp.h \
		pcre2/src/pcre2posix.h \
		pcre2/src/regex.h file/src/apprentice.c \
		file/src/apptype.c \
		file/src/ascmagic.c \
		file/src/asctime_r.c \
		file/src/asprintf.c \
		file/src/buffer.c \
		file/src/cdf.c \
		file/src/cdf_time.c \
		file/src/compress.c \
		file/src/ctime_r.c \
		file/src/der.c \
		file/src/dprintf.c \
		file/src/encoding.c \
		file/src/fmtcheck.c \
		file/src/fsmagic.c \
		file/src/funcs.c \
		file/src/getline.c \
		file/src/gmtime_r.c \
		file/src/is_csv.c \
		file/src/is_json.c \
		file/src/is_simh.c \
		file/src/is_tar.c \
		file/src/localtime_r.c \
		file/src/magic.c \
		file/src/pread.c \
		file/src/print.c \
		file/src/readcdf.c \
		file/src/readelf.c \
		file/src/seccomp.c \
		file/src/softmagic.c \
		file/src/strcasestr.c \
		file/src/strlcat.c \
		file/src/strlcpy.c \
		file/src/vasprintf.c \
		pcre2/src/pcre2_auto_possess.c \
		pcre2/src/pcre2_chartables.c \
		pcre2/src/pcre2_compile.c \
		pcre2/src/pcre2_config.c \
		pcre2/src/pcre2_context.c \
		pcre2/src/pcre2_convert.c \
		pcre2/src/pcre2_dfa_match.c \
		pcre2/src/pcre2_error.c \
		pcre2/src/pcre2_find_bracket.c \
		pcre2/src/pcre2_fuzzsupport.c \
		pcre2/src/pcre2_jit_compile.c \
		pcre2/src/pcre2_maketables.c \
		pcre2/src/pcre2_match.c \
		pcre2/src/pcre2_match_data.c \
		pcre2/src/pcre2_newline.c \
		pcre2/src/pcre2_ord2utf.c \
		pcre2/src/pcre2_pattern_info.c \
		pcre2/src/pcre2_serialize.c \
		pcre2/src/pcre2_string_utils.c \
		pcre2/src/pcre2_study.c \
		pcre2/src/pcre2_substitute.c \
		pcre2/src/pcre2_substring.c \
		pcre2/src/pcre2_tables.c \
		pcre2/src/pcre2_ucd.c \
		pcre2/src/pcre2_valid_utf.c \
		pcre2/src/pcre2_xclass.c \
		pcre2/src/pcre2posix.c
QMAKE_TARGET  = filetype
DESTDIR       = _bin/
TARGET        = libfiletype.a


first: all
####### Build rules

staticlib: _bin/$(TARGET)

_bin/libfiletype.a:  $(OBJECTS) $(OBJCOMP) 
	@test -d _bin/ || mkdir -p _bin/
	-$(DEL_FILE) _bin/$(TARGET)
	$(AR) $(DESTDIR)$(TARGET) $(OBJECTS)


Makefile: libfiletype.pro /usr/lib/qt/mkspecs/linux-g++/qmake.conf /usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/sanitize.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_Attica.pri \
		/usr/lib/qt/mkspecs/modules/qt_BluezQt.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivities.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivitiesStats.pri \
		/usr/lib/qt/mkspecs/modules/qt_KArchive.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuth.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuthCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCMUtils.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCrash.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDeclarative.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDESu.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDNSSD.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDSoapClient.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDSoapServer.pri \
		/usr/lib/qt/mkspecs/modules/qt_KEmoticons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KFileMetaData.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KHolidays.pri \
		/usr/lib/qt/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIdleTime.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_Kirigami2.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemModels.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuff.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuffCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifyConfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib/qt/mkspecs/modules/qt_KParts.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPeople.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPeopleWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPty.pri \
		/usr/lib/qt/mkspecs/modules/qt_KRunner.pri \
		/usr/lib/qt/mkspecs/modules/qt_KService.pri \
		/usr/lib/qt/mkspecs/modules/qt_KSyntaxHighlighting.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextEditor.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KUnitConversion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWallet.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandClient.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandServer.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdf.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdf_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_phonon4qt5.pri \
		/usr/lib/qt/mkspecs/modules/qt_Prison.pri \
		/usr/lib/qt/mkspecs/modules/qt_QuickAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_Solid.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri \
		/usr/lib/qt/mkspecs/modules/qt_Syndication.pri \
		/usr/lib/qt/mkspecs/modules/qt_ThreadWeaver.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/toolchain.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/link_ltcg.prf \
		/usr/lib/qt/mkspecs/features/ltcg.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qmake_use.prf \
		/usr/lib/qt/mkspecs/features/file_copies.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		libfiletype.pro
	$(QMAKE) -o Makefile libfiletype.pro
/usr/lib/qt/mkspecs/features/spec_pre.prf:
/usr/lib/qt/mkspecs/common/unix.conf:
/usr/lib/qt/mkspecs/common/linux.conf:
/usr/lib/qt/mkspecs/common/sanitize.conf:
/usr/lib/qt/mkspecs/common/gcc-base.conf:
/usr/lib/qt/mkspecs/common/gcc-base-unix.conf:
/usr/lib/qt/mkspecs/common/g++-base.conf:
/usr/lib/qt/mkspecs/common/g++-unix.conf:
/usr/lib/qt/mkspecs/qconfig.pri:
/usr/lib/qt/mkspecs/modules/qt_Attica.pri:
/usr/lib/qt/mkspecs/modules/qt_BluezQt.pri:
/usr/lib/qt/mkspecs/modules/qt_KActivities.pri:
/usr/lib/qt/mkspecs/modules/qt_KActivitiesStats.pri:
/usr/lib/qt/mkspecs/modules/qt_KArchive.pri:
/usr/lib/qt/mkspecs/modules/qt_KAuth.pri:
/usr/lib/qt/mkspecs/modules/qt_KAuthCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri:
/usr/lib/qt/mkspecs/modules/qt_KCMUtils.pri:
/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri:
/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KCrash.pri:
/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KDeclarative.pri:
/usr/lib/qt/mkspecs/modules/qt_KDESu.pri:
/usr/lib/qt/mkspecs/modules/qt_KDNSSD.pri:
/usr/lib/qt/mkspecs/modules/qt_KDSoapClient.pri:
/usr/lib/qt/mkspecs/modules/qt_KDSoapServer.pri:
/usr/lib/qt/mkspecs/modules/qt_KEmoticons.pri:
/usr/lib/qt/mkspecs/modules/qt_KFileMetaData.pri:
/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri:
/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KHolidays.pri:
/usr/lib/qt/mkspecs/modules/qt_KI18n.pri:
/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri:
/usr/lib/qt/mkspecs/modules/qt_KIdleTime.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_Kirigami2.pri:
/usr/lib/qt/mkspecs/modules/qt_KItemModels.pri:
/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri:
/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KNewStuff.pri:
/usr/lib/qt/mkspecs/modules/qt_KNewStuffCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri:
/usr/lib/qt/mkspecs/modules/qt_KNotifyConfig.pri:
/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri:
/usr/lib/qt/mkspecs/modules/qt_KParts.pri:
/usr/lib/qt/mkspecs/modules/qt_KPeople.pri:
/usr/lib/qt/mkspecs/modules/qt_KPeopleWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KPty.pri:
/usr/lib/qt/mkspecs/modules/qt_KRunner.pri:
/usr/lib/qt/mkspecs/modules/qt_KService.pri:
/usr/lib/qt/mkspecs/modules/qt_KSyntaxHighlighting.pri:
/usr/lib/qt/mkspecs/modules/qt_KTextEditor.pri:
/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KUnitConversion.pri:
/usr/lib/qt/mkspecs/modules/qt_KWallet.pri:
/usr/lib/qt/mkspecs/modules/qt_KWaylandClient.pri:
/usr/lib/qt/mkspecs/modules/qt_KWaylandServer.pri:
/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri:
/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_help.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_location.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_pdf.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_pdf_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webengine.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webengine_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/qt/mkspecs/modules/qt_phonon4qt5.pri:
/usr/lib/qt/mkspecs/modules/qt_Prison.pri:
/usr/lib/qt/mkspecs/modules/qt_QuickAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_Solid.pri:
/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri:
/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri:
/usr/lib/qt/mkspecs/modules/qt_Syndication.pri:
/usr/lib/qt/mkspecs/modules/qt_ThreadWeaver.pri:
/usr/lib/qt/mkspecs/features/qt_functions.prf:
/usr/lib/qt/mkspecs/features/qt_config.prf:
/usr/lib/qt/mkspecs/linux-g++/qmake.conf:
/usr/lib/qt/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/qt/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt/mkspecs/features/toolchain.prf:
/usr/lib/qt/mkspecs/features/default_pre.prf:
/usr/lib/qt/mkspecs/features/resolve_config.prf:
/usr/lib/qt/mkspecs/features/default_post.prf:
/usr/lib/qt/mkspecs/features/link_ltcg.prf:
/usr/lib/qt/mkspecs/features/ltcg.prf:
/usr/lib/qt/mkspecs/features/warn_on.prf:
/usr/lib/qt/mkspecs/features/qmake_use.prf:
/usr/lib/qt/mkspecs/features/file_copies.prf:
/usr/lib/qt/mkspecs/features/testcase_targets.prf:
/usr/lib/qt/mkspecs/features/exceptions.prf:
/usr/lib/qt/mkspecs/features/yacc.prf:
/usr/lib/qt/mkspecs/features/lex.prf:
libfiletype.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile libfiletype.pro

qmake_all: FORCE


all: Makefile _bin/libfiletype.a

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) _bin/$(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

benchmark: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

apprentice.o: file/src/apprentice.c file/src/file.h \
		misc/config.h \
		misc/file_config.h \
		misc/pcre2_config.h \
		pcre2/src/regex.h \
		misc/magic.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o apprentice.o file/src/apprentice.c

apptype.o: file/src/apptype.c file/src/file.h \
		misc/config.h \
		misc/file_config.h \
		misc/pcre2_config.h \
		pcre2/src/regex.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o apptype.o file/src/apptype.c

ascmagic.o: file/src/ascmagic.c file/src/file.h \
		misc/config.h \
		misc/file_config.h \
		misc/pcre2_config.h \
		pcre2/src/regex.h \
		misc/magic.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ascmagic.o file/src/ascmagic.c

asctime_r.o: file/src/asctime_r.c file/src/file.h \
		misc/config.h \
		misc/file_config.h \
		misc/pcre2_config.h \
		pcre2/src/regex.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o asctime_r.o file/src/asctime_r.c

asprintf.o: file/src/asprintf.c file/src/file.h \
		misc/config.h \
		misc/file_config.h \
		misc/pcre2_config.h \
		pcre2/src/regex.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o asprintf.o file/src/asprintf.c

buffer.o: file/src/buffer.c file/src/file.h \
		misc/config.h \
		misc/file_config.h \
		misc/pcre2_config.h \
		pcre2/src/regex.h \
		misc/magic.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o buffer.o file/src/buffer.c

cdf.o: file/src/cdf.c file/src/file.h \
		misc/config.h \
		misc/file_config.h \
		misc/pcre2_config.h \
		pcre2/src/regex.h \
		file/src/cdf.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o cdf.o file/src/cdf.c

cdf_time.o: file/src/cdf_time.c file/src/file.h \
		misc/config.h \
		misc/file_config.h \
		misc/pcre2_config.h \
		pcre2/src/regex.h \
		file/src/cdf.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o cdf_time.o file/src/cdf_time.c

compress.o: file/src/compress.c file/src/file.h \
		misc/config.h \
		misc/file_config.h \
		misc/pcre2_config.h \
		pcre2/src/regex.h \
		misc/magic.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o compress.o file/src/compress.c

ctime_r.o: file/src/ctime_r.c file/src/file.h \
		misc/config.h \
		misc/file_config.h \
		misc/pcre2_config.h \
		pcre2/src/regex.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ctime_r.o file/src/ctime_r.c

der.o: file/src/der.c file/src/file.h \
		misc/config.h \
		misc/file_config.h \
		misc/pcre2_config.h \
		pcre2/src/regex.h \
		misc/magic.h \
		file/src/der.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o der.o file/src/der.c

dprintf.o: file/src/dprintf.c file/src/file.h \
		misc/config.h \
		misc/file_config.h \
		misc/pcre2_config.h \
		pcre2/src/regex.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o dprintf.o file/src/dprintf.c

encoding.o: file/src/encoding.c file/src/file.h \
		misc/config.h \
		misc/file_config.h \
		misc/pcre2_config.h \
		pcre2/src/regex.h \
		misc/magic.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o encoding.o file/src/encoding.c

fmtcheck.o: file/src/fmtcheck.c file/src/file.h \
		misc/config.h \
		misc/file_config.h \
		misc/pcre2_config.h \
		pcre2/src/regex.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o fmtcheck.o file/src/fmtcheck.c

fsmagic.o: file/src/fsmagic.c file/src/file.h \
		misc/config.h \
		misc/file_config.h \
		misc/pcre2_config.h \
		pcre2/src/regex.h \
		misc/magic.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o fsmagic.o file/src/fsmagic.c

funcs.o: file/src/funcs.c file/src/file.h \
		misc/config.h \
		misc/file_config.h \
		misc/pcre2_config.h \
		pcre2/src/regex.h \
		misc/magic.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o funcs.o file/src/funcs.c

getline.o: file/src/getline.c file/src/file.h \
		misc/config.h \
		misc/file_config.h \
		misc/pcre2_config.h \
		pcre2/src/regex.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o getline.o file/src/getline.c

gmtime_r.o: file/src/gmtime_r.c file/src/file.h \
		misc/config.h \
		misc/file_config.h \
		misc/pcre2_config.h \
		pcre2/src/regex.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o gmtime_r.o file/src/gmtime_r.c

is_csv.o: file/src/is_csv.c file/src/file.h \
		misc/config.h \
		misc/file_config.h \
		misc/pcre2_config.h \
		pcre2/src/regex.h \
		misc/magic.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o is_csv.o file/src/is_csv.c

is_json.o: file/src/is_json.c file/src/file.h \
		misc/config.h \
		misc/file_config.h \
		misc/pcre2_config.h \
		pcre2/src/regex.h \
		misc/magic.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o is_json.o file/src/is_json.c

is_simh.o: file/src/is_simh.c file/src/file.h \
		misc/config.h \
		misc/file_config.h \
		misc/pcre2_config.h \
		pcre2/src/regex.h \
		misc/magic.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o is_simh.o file/src/is_simh.c

is_tar.o: file/src/is_tar.c file/src/file.h \
		misc/config.h \
		misc/file_config.h \
		misc/pcre2_config.h \
		pcre2/src/regex.h \
		misc/magic.h \
		file/src/tar.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o is_tar.o file/src/is_tar.c

localtime_r.o: file/src/localtime_r.c file/src/file.h \
		misc/config.h \
		misc/file_config.h \
		misc/pcre2_config.h \
		pcre2/src/regex.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o localtime_r.o file/src/localtime_r.c

magic.o: file/src/magic.c file/src/file.h \
		misc/config.h \
		misc/file_config.h \
		misc/pcre2_config.h \
		pcre2/src/regex.h \
		misc/magic.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o magic.o file/src/magic.c

pread.o: file/src/pread.c file/src/file.h \
		misc/config.h \
		misc/file_config.h \
		misc/pcre2_config.h \
		pcre2/src/regex.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pread.o file/src/pread.c

print.o: file/src/print.c file/src/file.h \
		misc/config.h \
		misc/file_config.h \
		misc/pcre2_config.h \
		pcre2/src/regex.h \
		file/src/cdf.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o print.o file/src/print.c

readcdf.o: file/src/readcdf.c file/src/file.h \
		misc/config.h \
		misc/file_config.h \
		misc/pcre2_config.h \
		pcre2/src/regex.h \
		file/src/cdf.h \
		misc/magic.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o readcdf.o file/src/readcdf.c

readelf.o: file/src/readelf.c file/src/file.h \
		misc/config.h \
		misc/file_config.h \
		misc/pcre2_config.h \
		pcre2/src/regex.h \
		file/src/readelf.h \
		misc/magic.h \
		file/src/elfclass.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o readelf.o file/src/readelf.c

seccomp.o: file/src/seccomp.c file/src/file.h \
		misc/config.h \
		misc/file_config.h \
		misc/pcre2_config.h \
		pcre2/src/regex.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o seccomp.o file/src/seccomp.c

softmagic.o: file/src/softmagic.c file/src/file.h \
		misc/config.h \
		misc/file_config.h \
		misc/pcre2_config.h \
		pcre2/src/regex.h \
		misc/magic.h \
		file/src/der.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o softmagic.o file/src/softmagic.c

strcasestr.o: file/src/strcasestr.c file/src/file.h \
		misc/config.h \
		misc/file_config.h \
		misc/pcre2_config.h \
		pcre2/src/regex.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o strcasestr.o file/src/strcasestr.c

strlcat.o: file/src/strlcat.c file/src/file.h \
		misc/config.h \
		misc/file_config.h \
		misc/pcre2_config.h \
		pcre2/src/regex.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o strlcat.o file/src/strlcat.c

strlcpy.o: file/src/strlcpy.c file/src/file.h \
		misc/config.h \
		misc/file_config.h \
		misc/pcre2_config.h \
		pcre2/src/regex.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o strlcpy.o file/src/strlcpy.c

vasprintf.o: file/src/vasprintf.c file/src/file.h \
		misc/config.h \
		misc/file_config.h \
		misc/pcre2_config.h \
		pcre2/src/regex.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o vasprintf.o file/src/vasprintf.c

pcre2_auto_possess.o: pcre2/src/pcre2_auto_possess.c misc/config.h \
		misc/file_config.h \
		misc/pcre2_config.h \
		pcre2/src/pcre2_internal.h \
		misc/pcre2.h \
		pcre2/src/pcre2_ucp.h \
		pcre2/src/pcre2_intmodedep.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pcre2_auto_possess.o pcre2/src/pcre2_auto_possess.c

pcre2_chartables.o: pcre2/src/pcre2_chartables.c misc/config.h \
		misc/file_config.h \
		misc/pcre2_config.h \
		pcre2/src/pcre2_internal.h \
		misc/pcre2.h \
		pcre2/src/pcre2_ucp.h \
		pcre2/src/pcre2_intmodedep.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pcre2_chartables.o pcre2/src/pcre2_chartables.c

pcre2_compile.o: pcre2/src/pcre2_compile.c misc/pcre2_config.h \
		pcre2/src/pcre2_internal.h \
		misc/pcre2.h \
		pcre2/src/pcre2_ucp.h \
		pcre2/src/pcre2_intmodedep.h \
		pcre2/src/pcre2_printint.c
	$(CC) -c $(CFLAGS) $(INCPATH) -o pcre2_compile.o pcre2/src/pcre2_compile.c

pcre2_config.o: pcre2/src/pcre2_config.c misc/pcre2_config.h \
		pcre2/src/pcre2_internal.h \
		misc/pcre2.h \
		pcre2/src/pcre2_ucp.h \
		pcre2/src/pcre2_intmodedep.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pcre2_config.o pcre2/src/pcre2_config.c

pcre2_context.o: pcre2/src/pcre2_context.c misc/pcre2_config.h \
		pcre2/src/pcre2_internal.h \
		misc/pcre2.h \
		pcre2/src/pcre2_ucp.h \
		pcre2/src/pcre2_intmodedep.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pcre2_context.o pcre2/src/pcre2_context.c

pcre2_convert.o: pcre2/src/pcre2_convert.c misc/pcre2_config.h \
		pcre2/src/pcre2_internal.h \
		misc/pcre2.h \
		pcre2/src/pcre2_ucp.h \
		pcre2/src/pcre2_intmodedep.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pcre2_convert.o pcre2/src/pcre2_convert.c

pcre2_dfa_match.o: pcre2/src/pcre2_dfa_match.c misc/pcre2_config.h \
		pcre2/src/pcre2_internal.h \
		misc/pcre2.h \
		pcre2/src/pcre2_ucp.h \
		pcre2/src/pcre2_intmodedep.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pcre2_dfa_match.o pcre2/src/pcre2_dfa_match.c

pcre2_error.o: pcre2/src/pcre2_error.c misc/pcre2_config.h \
		pcre2/src/pcre2_internal.h \
		misc/pcre2.h \
		pcre2/src/pcre2_ucp.h \
		pcre2/src/pcre2_intmodedep.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pcre2_error.o pcre2/src/pcre2_error.c

pcre2_find_bracket.o: pcre2/src/pcre2_find_bracket.c misc/pcre2_config.h \
		pcre2/src/pcre2_internal.h \
		misc/pcre2.h \
		pcre2/src/pcre2_ucp.h \
		pcre2/src/pcre2_intmodedep.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pcre2_find_bracket.o pcre2/src/pcre2_find_bracket.c

pcre2_fuzzsupport.o: pcre2/src/pcre2_fuzzsupport.c misc/pcre2.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pcre2_fuzzsupport.o pcre2/src/pcre2_fuzzsupport.c

pcre2_jit_compile.o: pcre2/src/pcre2_jit_compile.c misc/pcre2_config.h \
		pcre2/src/pcre2_internal.h \
		misc/pcre2.h \
		pcre2/src/pcre2_ucp.h \
		pcre2/src/pcre2_intmodedep.h \
		pcre2/src/sljit/sljitLir.c \
		pcre2/src/sljit/sljitLir.h \
		pcre2/src/sljit/sljitConfig.h \
		pcre2/src/sljit/sljitConfigInternal.h \
		pcre2/src/sljit/sljitUtils.c \
		pcre2/src/sljit/sljitProtExecAllocator.c \
		pcre2/src/sljit/sljitExecAllocator.c \
		pcre2/src/sljit/sljitNativeX86_common.c \
		pcre2/src/sljit/sljitNativeX86_32.c \
		pcre2/src/sljit/sljitNativeX86_64.c \
		pcre2/src/sljit/sljitNativeARM_32.c \
		pcre2/src/sljit/sljitNativeARM_T2_32.c \
		pcre2/src/sljit/sljitNativeARM_64.c \
		pcre2/src/sljit/sljitNativePPC_common.c \
		pcre2/src/sljit/sljitNativePPC_32.c \
		pcre2/src/sljit/sljitNativePPC_64.c \
		pcre2/src/sljit/sljitNativeMIPS_common.c \
		pcre2/src/sljit/sljitNativeMIPS_32.c \
		pcre2/src/sljit/sljitNativeMIPS_64.c \
		pcre2/src/sljit/sljitNativeSPARC_common.c \
		pcre2/src/sljit/sljitNativeSPARC_32.c \
		pcre2/src/sljit/sljitNativeTILEGX_64.c \
		pcre2/src/sljit/sljitNativeTILEGX-encoder.c \
		pcre2/src/pcre2_jit_match.c \
		pcre2/src/pcre2_jit_misc.c
	$(CC) -c $(CFLAGS) $(INCPATH) -o pcre2_jit_compile.o pcre2/src/pcre2_jit_compile.c

pcre2_maketables.o: pcre2/src/pcre2_maketables.c misc/config.h \
		misc/file_config.h \
		misc/pcre2_config.h \
		pcre2/src/pcre2_internal.h \
		misc/pcre2.h \
		pcre2/src/pcre2_ucp.h \
		pcre2/src/pcre2_intmodedep.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pcre2_maketables.o pcre2/src/pcre2_maketables.c

pcre2_match.o: pcre2/src/pcre2_match.c misc/pcre2_config.h \
		pcre2/src/pcre2_internal.h \
		misc/pcre2.h \
		pcre2/src/pcre2_ucp.h \
		pcre2/src/pcre2_intmodedep.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pcre2_match.o pcre2/src/pcre2_match.c

pcre2_match_data.o: pcre2/src/pcre2_match_data.c misc/pcre2_config.h \
		pcre2/src/pcre2_internal.h \
		misc/pcre2.h \
		pcre2/src/pcre2_ucp.h \
		pcre2/src/pcre2_intmodedep.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pcre2_match_data.o pcre2/src/pcre2_match_data.c

pcre2_newline.o: pcre2/src/pcre2_newline.c misc/pcre2_config.h \
		pcre2/src/pcre2_internal.h \
		misc/pcre2.h \
		pcre2/src/pcre2_ucp.h \
		pcre2/src/pcre2_intmodedep.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pcre2_newline.o pcre2/src/pcre2_newline.c

pcre2_ord2utf.o: pcre2/src/pcre2_ord2utf.c misc/pcre2_config.h \
		pcre2/src/pcre2_internal.h \
		misc/pcre2.h \
		pcre2/src/pcre2_ucp.h \
		pcre2/src/pcre2_intmodedep.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pcre2_ord2utf.o pcre2/src/pcre2_ord2utf.c

pcre2_pattern_info.o: pcre2/src/pcre2_pattern_info.c misc/pcre2_config.h \
		pcre2/src/pcre2_internal.h \
		misc/pcre2.h \
		pcre2/src/pcre2_ucp.h \
		pcre2/src/pcre2_intmodedep.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pcre2_pattern_info.o pcre2/src/pcre2_pattern_info.c

pcre2_serialize.o: pcre2/src/pcre2_serialize.c misc/pcre2_config.h \
		pcre2/src/pcre2_internal.h \
		misc/pcre2.h \
		pcre2/src/pcre2_ucp.h \
		pcre2/src/pcre2_intmodedep.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pcre2_serialize.o pcre2/src/pcre2_serialize.c

pcre2_string_utils.o: pcre2/src/pcre2_string_utils.c misc/pcre2_config.h \
		pcre2/src/pcre2_internal.h \
		misc/pcre2.h \
		pcre2/src/pcre2_ucp.h \
		pcre2/src/pcre2_intmodedep.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pcre2_string_utils.o pcre2/src/pcre2_string_utils.c

pcre2_study.o: pcre2/src/pcre2_study.c misc/pcre2_config.h \
		pcre2/src/pcre2_internal.h \
		misc/pcre2.h \
		pcre2/src/pcre2_ucp.h \
		pcre2/src/pcre2_intmodedep.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pcre2_study.o pcre2/src/pcre2_study.c

pcre2_substitute.o: pcre2/src/pcre2_substitute.c misc/pcre2_config.h \
		pcre2/src/pcre2_internal.h \
		misc/pcre2.h \
		pcre2/src/pcre2_ucp.h \
		pcre2/src/pcre2_intmodedep.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pcre2_substitute.o pcre2/src/pcre2_substitute.c

pcre2_substring.o: pcre2/src/pcre2_substring.c misc/pcre2_config.h \
		pcre2/src/pcre2_internal.h \
		misc/pcre2.h \
		pcre2/src/pcre2_ucp.h \
		pcre2/src/pcre2_intmodedep.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pcre2_substring.o pcre2/src/pcre2_substring.c

pcre2_tables.o: pcre2/src/pcre2_tables.c misc/config.h \
		misc/file_config.h \
		misc/pcre2_config.h \
		pcre2/src/pcre2_internal.h \
		misc/pcre2.h \
		pcre2/src/pcre2_ucp.h \
		pcre2/src/pcre2_intmodedep.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pcre2_tables.o pcre2/src/pcre2_tables.c

pcre2_ucd.o: pcre2/src/pcre2_ucd.c misc/config.h \
		misc/file_config.h \
		misc/pcre2_config.h \
		pcre2/src/pcre2_internal.h \
		misc/pcre2.h \
		pcre2/src/pcre2_ucp.h \
		pcre2/src/pcre2_intmodedep.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pcre2_ucd.o pcre2/src/pcre2_ucd.c

pcre2_valid_utf.o: pcre2/src/pcre2_valid_utf.c misc/config.h \
		misc/file_config.h \
		misc/pcre2_config.h \
		pcre2/src/pcre2_internal.h \
		misc/pcre2.h \
		pcre2/src/pcre2_ucp.h \
		pcre2/src/pcre2_intmodedep.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pcre2_valid_utf.o pcre2/src/pcre2_valid_utf.c

pcre2_xclass.o: pcre2/src/pcre2_xclass.c misc/pcre2_config.h \
		pcre2/src/pcre2_internal.h \
		misc/pcre2.h \
		pcre2/src/pcre2_ucp.h \
		pcre2/src/pcre2_intmodedep.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pcre2_xclass.o pcre2/src/pcre2_xclass.c

pcre2posix.o: pcre2/src/pcre2posix.c misc/pcre2_config.h \
		misc/pcre2.h \
		pcre2/src/pcre2posix.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pcre2posix.o pcre2/src/pcre2posix.c

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

